DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS client_contacts;

CREATE TABLE IF NOT EXISTS client
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE                         NOT NULL DEFAULT NOW(),
    name    VARCHAR(255)                                        NOT NULL,
    surname VARCHAR(255)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS client_contacts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    contact       text                                    NOT NULL,
    contacts_type text                                    NOT NULL,
    client_id     BIGINT references client (id)
);
